FROM ruby:alpine
LABEL maintainer=jon@jaggersoft.com

RUN gem install simplecov hirb
ARG SIMPLECOV_DIR='/usr/local/bundle/gems/simplecov-0.17.1/lib'
RUN [ -d ${SIMPLECOV_DIR} ]
COPY simplecov-console.rb ${SIMPLECOV_DIR}
